### ISSUE TITLE
Broke an entiere session

### ISSUE THREAD

**Issue by albahaca1024254** [fearnworks/ComfyUI_FearnworksNodes#14]
After uninstalling the node had to delete the workflow and star anew just to generate a proper image anything related to the nodes is broken, I now load images perfectly generated to get the workflow template again and then run the queue again to only get broken noisy images, how is this even possible without altering any value on multiple previously functional workflows?, your work sir feels more like a virus than anything else, have a good day... Sir...

**Comment by fearnworks** [comment]
Sorry to hear about your issues. Project is not up to date with the recent comfyui changes and errors likely stem from that. I'll go ahead and archive the project for now.
