### ISSUE TITLE
Poor install instructions - May need to improve those!

### ISSUE THREAD

**Issue by AlexData-Hawkhill** [fearnworks/ComfyUI_FearnworksNodes#6]
A. Missing info on other NODES (Dependencies) one need to run the EXAMPLE .json that comes with this project.
(Missing: _"String Literal" , "JWIntergerToString" and "ShowText|pysssss"_)

B. Install guide missing, so I wrote one for Windows. See below. Feel free to use it!

------------------------------------
INSTALL GUIDE FOR WINDOWS:
------------------------------------
1. INSTALL **GIT** FOW WINDOWS LOCALLY ON YOUR WINDOWS PC FIRST! (Google it) !!

2. Then go to the folder where COMFYUI is installed (example:: **DRIVE:\FOLDER\ComfyUI\**)
and open a DOS/CMD window by erasing all text in the address bar, and writing CMD then press ENTER.
This should open up a DOS/CMD window in the folder you have COMFYUI installed in.
Now run the following DOS/CMD command from that folder:

**git clone https://github.com/fearnworks/ComfyUI_FearnworksNodes.git .\ComfyUI\custom_nodes\ComfyUI_FearnworksNodes**
OR...
**git clone https://github.com/fearnworks/ComfyUI_FearnworksNodes .\ComfyUI\custom_nodes\ComfyUI_FearnworksNodes**

One of these should clone the files into the folder "**ComfyUI\custom_nodes\ComfyUI_FearnworksNodes**".
If for some weird reason this fails, you can try one of the two following commands from the same CMD/DOS window:

**python_embeded\python.exe -c "import git; git.Repo.clone_from('https://github.com/fearnworks/ComfyUI_FearnworksNodes', 'ComfyUI\custom_nodes\ComfyUI_FearnworksNodes')"**
OR...
**.python_embeded\python.exe -c "import git; git.Repo.clone_from('https://github.com/fearnworks/ComfyUI_FearnworksNodes', 'ComfyUI\custom_nodes\ComfyUI_FearnworksNodes')"**

Then you need to MANUALLY MOVE (or copy) the file "**fw_nodes.py**" from **\ComfyUI\custom_nodes\ComfyUI_FearnworksNodes\** to **\ComfyUI\custom_nodes\** (_the folder one step/level back_)
Now restart ComfyUI and you will have the FearnworksNodes installed.

-Linux should be very similar, using GIT and the commands above to CLONE, but I don't have Linux, so no guide for Linux, sorry!
Guide By AlexData 2024.

**Comment by fearnworks** [comment]
Revisiting this repo after a bit of time away. Reworking the import process now to work from ComfyUI_Manager easily on the main 3 os distributions.  #7
